name: Resume

on: [push]

jobs:
  Generate-PDF:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install XeLaTeX
        run: sudo apt-get install texlive-xetex
      - name: Make zh
        run: make zh
      - name: Make en
        run: make en
      - name: Make photo
        run: make photo
      - uses: actions/upload-artifact@v3
        with:
          name: resume
          path: ./*.pdf
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
